MedusaII/urls.py
#  Developed by Vinicius José Fritzen
#  Last Modified 20/04/19 08:49.
#  Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini

from django.views.defaults import server_error, page_not_found
from django.contrib import admin
from django.http import HttpResponseServerError
from django.urls import include, path

from MedusaII import settings

urlpatterns = \
    [
        path('admin/', admin.site.urls),
        path('accounts/', include('escola.urlsAuth')),
        # path('escola/', include('escola.urls')),
        path('', include('escola.urls')),
        path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
        path('', include('pwa.urls')),
        path('maintenance-mode/', include('maintenance_mode.urls')),
        path('markdownx/', include('markdownx.urls')),
        path('select2/', include('django_select2.urls')),
    ]
if settings.DEBUG:
    urlpatterns.append(path('500', server_error))
    urlpatterns.append(path('404', page_not_found))


handler500 = 'escola.views.handler500'

escola/urls.py
#  Developed by Vinicius José Fritzen
#  Last Modified 20/04/19 08:59.
#  Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini

from django.urls import include, path
from rest_framework import routers

import escola.views_aluno
import escola.views_cargo
import escola.views_conteudo
import escola.views_horario
import escola.views_materia
import escola.views_professor
import escola.views_tarefa
import escola.views_turma
from escola import api, views_profile, views_provas_marcadas
from escola.quotes.quotes_views import AllQuotesView
from escola.views_aviso import (AvisoDetailView, AvisoMixedCreateView,
                                AvisoTurmaCreateView)
from escola.views_feedback import FeedbackView

from . import views

router = routers.DefaultRouter()
router.register(r'users', api.UserViewSet)
router.register(r'groups', api.GroupViewSet)
router.register(r'profile', api.ProfileViewSet)
router.register(r'turma', api.TurmaViewSet)
router.register(r'seguidormanager', api.SeguidorManagerViewSet)
router.register(r'cargoturma', api.CargoTurmaViewSet)
router.register(r'professor', api.ProfessorViewSet)
router.register(r'materiadaturma', api.MateriaDaTurmaViewSet)
router.register(r'aluno', api.AlunoViewSet)
router.register(r'tarefa', api.TarefaViewSet)
router.register(r'tarefacompletacao', api.TarefaCompletacaoViewSet)
router.register(r'tarefacomentario', api.TarefaComentarioViewSet)
router.register(r'notificacao', api.NotificacaoViewSet)
router.register(r'horario', api.HorarioViewSet)
router.register(r'turno', api.TurnoViewSet)
router.register(r'turnoaula', api.TurnoAulaViewSet)
router.register(r'conteudo', api.ConteudoViewSet)
router.register(r'link_conteudo', api.LinkConteudoViewSet)
router.register(r'categoria_conteudo', api.CategoriaConteudoViewSet)

app_name = 'escola'

urlpatterns = [
    path('api/v1/', include(router.urls)),
    path('', views.index, name='index'),
    # turma
    path('turmas/', escola.views_turma.list_turmas, name='list-turmas'),
    path('turmas/add/', escola.views_turma.add_turma, name='add-turma'),
    path('turmas/<int:pk>', escola.views_turma.TurmaDetailView.as_view(), name='detail-turma'),
    path('turmas/<int:pk>/edit', escola.views_turma.edit_turma, name='edit-turma'),
    path('turmas/<int:pk>/delete', escola.views_turma.delete_turma, name='delete-turma'),
    path('alunos/populate/', escola.views_aluno.populate_alunos, name='populate-alunos'),
    # cargos
    path('turmas/<int:pk_turma>/cargos', escola.views_cargo.list_cargos, name='list-cargos'),
    path('turmas/<int:turma_pk>/cargos/add', escola.views_cargo.add_cargo, name='add-cargo'),
    path('turmas/cargos/edit/<int:pk>', escola.views_cargo.edit_cargo, name='edit-cargo'),
    path('turmas/cargos/delete/<int:pk>', escola.views_cargo.delete_cargo, name='delete-cargo'),
    # alunos
    path('turma/<int:turma_pk>/alunos', escola.views_aluno.list_alunos, name='list-alunos'),
    path('turma/<int:turma_pk>/alunos/add', escola.views_aluno.add_aluno, name='add-aluno'),
    path('turmas/aluno/<int:aluno_pk>/edit', views.edit_aluno, name='edit-aluno'),
    path('turmas/aluno/<int:aluno_pk>/delete', views.delete_aluno, name='delete-aluno'),
    # horario
    path('turma/<int:turma_pk>/horario', escola.views_horario.ver_horario, name='show-horario'),
    path('turma/<int:turma_pk>/horario/edit/<int:turno_cod>/<int:dia_cod>', escola.views_horario.alterar_horario,
         name='alterar-horario'),
    # professores
    path('professores/add', escola.views_professor.add_professor, name='add-professor'),
    path('professores/', escola.views_professor.list_professores, name='list-professores'),
    path('professor/<int:pk>/edit', escola.views_professor.edit_professor, name='edit-professor'),
    path('professor/<int:pk>/delete', escola.views_professor.delete_professor, name='delete-professor'),
    # materias
    path('turma/<int:turma_pk>/materias/add', escola.views_materia.add_materia, name='add-materia'),
    path('turma/<int:turma_pk>/materias', escola.views_materia.list_materias, name='list-materias'),
    path('materia/<int:materia_pk>/edit', escola.views_materia.edit_materia, name='edit-materia'),
    path('materia/<int:materia_pk>/delete', escola.views_materia.delete_materia,
         name='delete-materia'),
    path('materia/<int:pk>', escola.views_materia.MateriaDaTurmaDetailView.as_view(),
         name='detail-materia'),
    # tarefa
    path('turma/<int:turma_pk>/tarefas/add', escola.views_tarefa.add_tarefa, name='add-tarefa'),
    path('turma/<int:turma_pk>/tarefas', escola.views_tarefa.list_tarefa, name='list-tarefa'),
    path('turma/tarefa/<int:tarefa_pk>/edit', escola.views_tarefa.edit_tarefa, name='edit-tarefa'),
    path('turma/tarefa/<int:tarefa_pk>/delete', escola.views_tarefa.delete_tarefa, name='delete-tarefa'),
    path('turma/tarefa/<int:tarefa_pk>/concluir', escola.views_tarefa.concluir_tarefa, name='concluir-tarefa'),
    path('turma/tarefa/<int:tarefa_pk>', escola.views_tarefa.detalhes_tarefa, name='detalhes-tarefa'),
    # Seguir
    path('seguir/<int:pk>', views.seguir_manager, name='seguir'),
]

# Conteudos
urlpatterns += \
    [
        path('conteudo/<int:pk>',
             escola.views_conteudo.ConteudoDetail.as_view(),
             name='conteudo-detail'),
        path('conteudo/add/<int:pk_parent>',
             escola.views_conteudo.ConteudoCreate.as_view(),
             name='conteudo_add'),  # TODO: 13/04/2019 por wwwvi: Nomenclatura errada, mudar para add-conteudo
        path('conteudo/add/',
             escola.views_conteudo.ConteudoCreate.as_view(),
             name='conteudo_add'),  # TODO TAMBEM
        path('materia/<int:materia>/addConteudos',
             escola.views_conteudo.addConteudosAMateria.as_view(),
             name='add-conteudo-materia'),
        path('conteudo/<int:pk>/add', escola.views_conteudo.LinkConteudoCreateView.as_view(), name='add-link-conteudo'),
        path('link-conteudo/<int:pk>/remove', escola.views_conteudo.RemoveLinkFromConteudoView.as_view(), name='delete-link-conteudo'),
        path('conteudo/<int:pk>/add/<int:cat>', escola.views_conteudo.LinkConteudoCreateView.as_view(), name='add-link-conteudo'),
        path('conteudo/<int:pk>/edit', escola.views_conteudo.ConteudoUpdateView.as_view(), name='update-conteudo'),
        path('conteudo/<int:pk>/add-to-materias', escola.views_conteudo.AdicionarAVariasMateriasView.as_view(), name='adicionar-conteudo-a-varias-materias'),
    ]

# Notificações
urlpatterns += \
    [
        path('notificacoes', escola.views.NotificacaoListView.as_view(), name='notificacoes-list'),
        path('update-email', escola.views.atualisar_emails, name='update-email')
    ]

# Pagina de sobre
urlpatterns += \
    [
        path('sobre', escola.views.SobreView.as_view(), name='sobre'),
    ]

# Paginas do professor
urlpatterns += \
    [
        path('self/materias', escola.views_professor.MateriaProfessorListView.as_view(), name='materias_professor'),  # TODO: 13/04/2019 por wwwvi: Alterar name, nomeclatura esta errada
        path('self/conteudos', escola.views_conteudo.MeusConteudosListView.as_view(), name='conteudos-professor'),
    ]

# Offline template
urlpatterns += \
    [
        path('base_layout', escola.views.base_layout, name='base_layout_offline'),
    ]

# Perfil do usuario
urlpatterns +=\
    [
        path('self/emailChange', views_profile.email_change, name='self-email-change'),
    ]

# Marcar Provas

urlpatterns +=\
    [
        path('turmas/<int:turma_pk>/provas', views_provas_marcadas.ListaProvasTurmaView.as_view(),
             name='provas-turma-list'),
        path('provas/add/materia', views_provas_marcadas.CreateProvaMateriaView.as_view(),
             name='marcar-prova-materia'),
        path('provas/add/area', views_provas_marcadas.CreateProvaAreaView.as_view(),
             name='marcar-prova-area'),
        path('self/provas', views_provas_marcadas.ListaProvasProfessorView.as_view(),
             name='provas-professor'),  # As provas do professor
        path('provas/materia/<int:pk>/delete', views_provas_marcadas.ProvaMateriaDeleteView.as_view(),
             name='provas-materia-delete'),
        path('provas/area/<int:pk>/delete', views_provas_marcadas.ProvaAreaDeleteView.as_view(),
             name='provas-area-delete'),
        path('provas/<int:pk>', views_provas_marcadas.ProvaDetailView.as_view(),
             name='prova-detail'),
        path('turmas/<int:pk>/dias_livres', views_provas_marcadas.CalendarioTurmaDatasLivresView.as_view(),
             name='turma-provas-calendario'),
    ]

# Quotes

urlpatterns += \
    [
        path('all-quotes', AllQuotesView.as_view(), name='todas-quotes'),
    ]

# Feedback

urlpatterns += \
    [
        path('feedback', FeedbackView.as_view(), name='feedback'),
    ]

# Avisos

urlpatterns += \
    [
        path('aviso/add-turma',
             AvisoTurmaCreateView.as_view(),
             name='aviso-add-turma'),
             
        path('aviso/<int:pk>',
             AvisoDetailView.as_view(),
             name='aviso-detail'),

        path('aviso/add-mixed',
             AvisoMixedCreateView.as_view(),
             name='aviso-add-mixed')
    ]

# Temporarias

# urlpatterns += \
#     [
#           JAMAIS ADICIONAR NOVAMENTE, É DEBUG!!!
#         path('users/', escola.views.UserListView.as_view())
#     ]

escola/views.py
#  Developed by Vinicius José Fritzen
#  Last Modified 20/04/19 09:00.
#  Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini

import datetime
import logging

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, render_to_response
from django.template import RequestContext
from django.views.generic import ListView, TemplateView

from escola.models import (Horario, Notificacao, Notificador, Turma, Turno,
                           TurnoAula)

from .decorators import *
from .forms import *
from .models import *

logger = logging.getLogger(__name__)


@is_user_escola
@login_required
def index(request):
    logger.info('views:index; user_id: %s', request.user.pk)
    context = {'request': request}

    logger.info('Antes de renderizar a view index, user: %s', request.user.pk)

    if request.user.profile_escola.is_aluno:
        logger.info('É um aluno renderizando tela do aluno')
        context.update({'turma': request.user.aluno.turma})
        return render(request, 'escola/home_aluno.html', context=context)

    if request.user.profile_escola.is_professor:
        logger.info('É um professor renderizando tela do professor')
        return render(request, 'escola/home_professor.html', context=context)
    logger.warning('O usuario não é nem professor nem aluno, renderizando a tela default')
    return render(request, 'escola/home_base.html', context=context)


@permission_required('escola.edit_aluno')
def edit_aluno():
    # TODO: Implement edit aluno
    raise NotImplementedError


@permission_required('escola.can_delete_aluno')
def delete_aluno(request, aluno_pk):
    aluno = get_object_or_404(Aluno, pk=aluno_pk)
    turma = aluno.turma
    aluno.delete()
    return HttpResponseRedirect(reverse('escola:list-alunos', args=[turma.pk]))


class SobreView(TemplateView):
    template_name = "escola/sobre.html"




@is_user_escola
@login_required
def seguir_manager(request, pk):
    seguidor = Notificador.objects.get(pk=pk)
    seguidor.adicionar_seguidor(request.user)
    return HttpResponseRedirect(request.GET.get('next', reverse('escola:index')))


class NotificacaoListView(LoginRequiredMixin, ListView):
    model = Notificacao
    template_name = "escola/notificacoes_list.html"
    context_object_name = 'notificacoes'

    def get_queryset(self):
        query = Notificacao.objects.filter(user=self.request.user).order_by('-dataCriado')
        self.request.user.profile_escola.read_all_notifications()
        return query


def handler404(request, exception, template_name="404.html"):
    response = render_to_response('404.html')
    response.status_code = 404
    return response


def handler500(request, template_name="500.html"):
    response = render_to_response('500.html', {'request': request})
    response.status_code = 500
    return response


def base_layout(request):
    template = 'escola/base.html'
    return render(request, template)


# class UserListView(ListView):
#     model = User
#     context_object_name = 'users'
#     template_name = 'listUser.html'


def atualisar_emails(request):
    Turma.atualizaProvas()
    Turma.atualizaTarefas()
    count = Notificacao.send_all_emails()
    return JsonResponse({'success': True, 'emails_sended': count})

escola/templates/escola/base.html
<!--
  ~ Developed by Vinicius José Fritzen
  ~ Last Modified 26/04/19 16:45.
  ~ Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini
  -->

{% extends "escola/base_imports.html" %}
{% block extrahead %}
{%endblock%}
{% block body %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Medusa II</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-item nav-link active" href="{% url 'escola:index' %}">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle"
           role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Escola
        </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'escola:list-turmas' %}">Lista de Turmas</a>
            <a class="dropdown-item" href="{% url 'escola:list-professores' %}">Lista de Professores</a>
        </div>
      </li>
      {% if user.profile_escola.is_aluno %}
      <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'escola:list-materias' user.aluno.turma.id %}">Matérias</a>
      </li>
      <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'escola:list-tarefa' user.aluno.turma.id %}">Tarefas</a>
      </li>
      <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'escola:detail-turma' user.aluno.turma.id %}">Minha Turma</a>
      </li>
      {%endif%}
      {% if user.profile_escola.is_professor%}
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown"
           role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Area do Professor
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a href="{%url 'escola:materias_professor'%}" class="dropdown-item">Minhas Disciplinas</a>
            <a href="{%url 'escola:conteudos-professor'%}" class="dropdown-item">Meus Conteudos</a>
            <a href="{%url 'escola:provas-professor'%}" class="dropdown-item">Minhas Provas</a>
        </div>
      </li>

      {%endif%}

      {%if user.is_staff%}
      <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'admin:index'%}">Admin</a>
      </li>
      {%endif%}
      <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'escola:sobre'%}">Sobre</a>
      </li>
    </ul>
  </div>
  {% if user.is_authenticated%}
  <span class="navbar-text">Olá, {{user.username}} </span>

  <a class="nav-item nav-link" href="{% url 'logout'%}">Sair</a>
  <a class="nav-item nav-link" href="{% url 'password_change'%}">Alterar senha</a>
  {%else%}
  <button class="btn btn-outline-success" type="button" onclick="window.location.href = '{%url 'login' %}';">Login
  </button>
  {% endif %}
  <div><a href="{% url 'escola:notificacoes-list'%}">
    <i class="fas fa-bell" style="color:Dodgerblue; font-size:21.5px;"></i>
    {%if user.profile_escola.template_data.notificacao_count != 0%}
    <span class="badge badge-light">{{user.profile_escola.template_data.notificacao_count}}</span>
    {%endif%}</a>
  </div>
  </div>
</nav>
{%if warnings%}
  <!--Avisos a serem exibidos-->
{%for warn in warnings%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{warn.message}}
    {%if warn.link_page_name%}
    <a href="{% url warn.link_page_name%}" >
      <i class="far fa-arrow-alt-circle-right"></i>
    </a>
    {%endif%}
    <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{%endfor%}
{%endif%}
{% endblock navbar %}

<!-- Bloco de conteúdo -->
<div class="container">
{% block conteudo %}{% endblock %}
</div>
<!--Feedback btn-->
<!--<a href="{%url 'escola:feedback'%}" id="feedback-btn" class="btn btn-info" style="
transform: rotate(-90deg);
transform-origin: 100% 100%;
position: fixed;
right: 0;
top: 50%;
z-index: 100;">
    Feedback</span>
</a>
<div id="feedback-modal" class="modal fade text-center">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>
-->
<!--Rodapé-->
<script src="https://desk.zoho.com/portal/api/feedbackwidget/404958000000121623?orgId=691522109&displayType=popout"></script>
{% endblock body %}

{% block feed_scripts %}
<!--
  <script>
      $('#feedback-btn').on('click', function(e){
        e.preventDefault();
        $('#feedback-modal').modal('show').find('.modal-content').load($(this).attr('href'));
      });
  </script>-->
{%endblock%}

escola/templates/escola/base_delete.html
{% extends "escola/base_imports.html" %}

{% block body %}
<div class="container">
  <a href="{%url 'escola:index'%}">Voltar a Pagina Inicial</a>
<form method="post" class="form">{% csrf_token %}
    <p>{% block message %} Você tem certeza que quer deletar {% endblock message %}"{{ object }}"?</p>
    <input type="submit" value="Sim, tenho certeza">
</form>
</div>
{% endblock body %}

escola/templates/escola/base_form.html
{% extends "escola/base.html" %}

{% load crispy_forms_tags %}
{% load sekizai_tags %}

{%block title%}Medusa II{%endblock%}

{% block conteudo %}
  {% block preform %}{% endblock preform %}

  {% block form %}
    {% crispy form %}
  {% endblock form %}
  {% addtoblock "js" %}
  <script>
  let element = document.getElementsByClassName('markdownx');

  Object.keys(element).map(key =>

      element[key].addEventListener('markdownx.update', event => MathJax.Hub.Queue(["Typeset",MathJax.Hub]))

  );
  </script>
  {% endaddtoblock %}
  {% addtoblock "js" %}
  {{ form.media.js }}
  {% endaddtoblock %}
  {% addtoblock "css" %}
  {{ form.media.css }}
  {% endaddtoblock %}
  {% block posform %}{% endblock posform %}
{% endblock %}

escola/templates/escola/conteudo_detail.html
{% extends "escola/base.html" %}

{%load dict_key markdown panels %}


{% block title %} {{conteudo.nome}} {% endblock %}


{% block conteudo %}
{% if is_owner %} <!--Verifica se o user é o professor-->
  {% if materias__len == 0 %}
        <div class="alert alert-danger" role="alert">
          <h4 class="alert-heading"><i class="fas fa-exclamation-triangle"></i>
          Sem matérias!</h4>
          <p>Este conteúdo não foi registrado em nenhuma matéria!
          Lembre-se de sempre registrar conteúdos em matérias, pois é assim que
          seus alunos podem vê-la. Use o botão abaixo, e selecione a
          que turmas você quer adiciona-la.</p>
          <hr>
          <a href="{%url 'escola:adicionar-conteudo-a-varias-materias' conteudo.pk%}" class="btn btn-primary">Adicionar à materias</a> <!--FIXME Faça este botão funcionar-->
        </div>
      {% else %}
        <div class="alert alert-success" role="alert">
          <h4 class="alert-heading">Este conteúdo está sendo apreciado! 
          <i class="far fa-smile"></i></h4>
          <p>Agradecemos por ter adicionado este conteúdo, muitos alunos, com
          toda a certeza, estão aproveitando esta fonte de conhecimento
          (bem, talvez não, mas é sempre bom ter esperança, não é mesmo?). 
          Continue adicionando conteúdos, links, e outros; tudo para melhorar a
          educação!</p>
          <hr>
          <strong>Veja as matérias e turmas que tem acesso:</strong>
          <ul>
            {% for materia in materias %}
              <li>{{materia}}</li>
            {% endfor %}
          </ul>
          <a href="{%url 'escola:adicionar-conteudo-a-varias-materias' conteudo.pk%}" class="btn btn-primary">Adicionar à materias</a> <!--FIXME Faça este botão funcionar-->
        </div>
      {% endif %}
    
{% endif %}


  <div class="jumbotron">

    <h1 class="display-4">{{conteudo.nome}}</h1>
    <p class="lead">{{conteudo.descricao|md}}</p>
  </div>
  <hr/>

  {%if conteudo.professor == user.professor%}
      <a href="{%url 'escola:add-link-conteudo' conteudo.pk%}" class="btn btn-primary">Novo Link</a>
  {%endif%}

  {% for categoria in categorias%}
  <div class="card">
    <div class="card-body">
      <h2 class="card-title" style="color: {{categoria.obj.cor}}"> {{categoria.obj.nome}} </h2>
      {%if conteudo.professor == user.professor%}
      <a href="{%url 'escola:add-link-conteudo' conteudo.pk categoria.obj.id%}" class="btn btn-primary">Novo Link</a>
      {%endif%}
      <div class="list-group">
        {%for link in categoria.links%}
        {% link_conteudo link %}
        {% endfor %}
      </div>
    </div>
  </div>
  {% endfor %}
{% endblock %}

escola/templates/escola/email_change.html
<!--
  ~ Developed by Vinicius José Fritzen
  ~ Last Modified 04/05/19 17:29.
  ~ Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini
  -->
{% extends "escola/base.html" %}
{% load crispy_forms_tags %}
{%load dict_key %}


{% block title %} Alterar Email - Medusa II {% endblock %}


{% block conteudo %}
<div class="container">
  {%crispy form%}
</div>
{% endblock %}

escola/templates/escola/home_aluno.html
{% extends "escola/home_base.html" %}
<!--
  ~ Developed by Vinicius José Fritzen
  ~ Last Modified 28/04/19 07:35.
  ~ Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini
  -->

{%load dict_key panels %}
{% block especific_cargo %}
<div  class="row">
    <div class="col">
        <h2>Horário</h2>
        {% panel_mostra_horario_proprio user %}
    </div>
</div> <br/>

<div class="row">
    <div class="col-md">
        <h2>Tarefas</h2>
        {%if perms.escola.can_add_tarefa%}
        <!-- TODO ageitar permissões e mover isso para outro lugar. -->
            <a href="{% url 'escola:add-tarefa' turma.pk %}" class="btn btn-primary">Adicionar Tarefa</a>
        {%endif%}
        {%panel_tarefas_aluno user%}
    </div>
    <div class="col-md">
        <h2>Provas marcadas</h2>
        {% panel_lista_provas_marcadas_turma user.aluno.turma 6%}
        <a href="{%url 'escola:provas-turma-list' turma.id%}" class="btn btn-secondary">Ver mais...</a>
    </div>
</div> <br/>
{%panel_quote%}
{% endblock especific_cargo %}

escola/templates/escola/home_professor.html
{% extends "escola/home_base.html" %}
<!--
  ~ Developed by Vinicius José Fritzen
  ~ Last Modified 28/04/19 07:35.
  ~ Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini
  -->

{%load dict_key %}
{% load panels %}
{% block especific_cargo %}

<section>
  {%panel_resumo_do_dia_prof user%}
</section>
<section>
{%panel_quote%}
</section>
{% endblock especific_cargo %}

escola/templates/escola/materiadaturma_detail.html
{% extends "escola/base.html" %}

{%load dict_key %}
{% load mptt_tags %}

{% block title %} {{materia.nome}} {% endblock %}

{% block styles %}
<style>
.just-padding {
  padding: 15px;
}

.list-group.list-group-root {
  padding: 0;
  overflow: hidden;
}

.list-group.list-group-root .list-group {
  margin-bottom: 0;
}

.list-group.list-group-root .list-group-item {
  border-radius: 0;
  border-width: 1px 0 0 0;
}

.list-group.list-group-root > .list-group-item:first-child {
  border-top-width: 0;
}

.list-group.list-group-root > .list-group > .list-group-item {
  padding-left: 40px;
}

.list-group.list-group-root > .list-group > .list-group > .list-group-item {
  padding-left: 55px;
}
.list-group.list-group-root > .list-group > .list-group >  .list-group > .list-group-item {
  padding-left: 70px;
}

</style>
{% endblock %}
{% block conteudo %}


<div class="container">

  <h1>{{materia.nome}}</h1>

  Prof. {{materia.professor.nome}}

  {% if materia.conteudos.all %}
  <h3>Conteudos:</h3>
  <div class="just-padding">
    <div class="list-group list-group-root well">
      {% recursetree materia.conteudos.all %}
      <a href="{% url 'escola:conteudo-detail' node.pk%}" class="list-group-item">{{ node.nome }}</a>
      {% if not node.is_leaf_node %}
      <div class="list-group">
        {{ children }}
      </div>
      {% endif %}
      {% endrecursetree %}
    </div>

    {% endif %}
  </div>
</div>


{% endblock %}